version: '1.0'

1:
	service: Отели - клиентская часть
	name: Кол-во заказов бронирований жилья
	metric: Orders
	type: Целевая метрика
	methodology: Кол-во успешных заказов с атрибуцией по платформам и по last click по каналам (сейчас работает не корретно)
	slices: Orders

2:
	service: Отели - клиентская часть
	name: Конверсия из раздела отелей в бронирование 
	metric: CR hotel to reservation
	type: Целевая метрика
	methodology: Кол-во уникальных сессий с бронированием\ кол-во уникальных сессий в разделе отелей
	slices: CR hotel to reservation

3:
	service: Отели - клиентская часть
	name: Конверсия из поиска в бронирование по платформам / каналам
	metric: CR search to reservation
	type: Целевая метрика
	methodology: Кол-во уникальных сессий с бронированием\ кол-во уникальных сессий с запущеным поиском
	slices: CR search to reservation

4:
	service: Отели - клиентская часть
	name: Конверсия из посещения детальной страницы в бронирование
	metric: CR detail to reservation
	type: proxy-метрика
	methodology: Кол-во уникальных сессий с бронированием\ кол-во уникальных сессий с посещением страницы отеля
	slices: CR detail to reservation

5:
	service: Отели - клиентская часть
	name: Конверсия из корзины в бронирование
	metric: CR cart to reservation
	type: proxy-метрика
	methodology: Кол-во уникальных сессий с бронированием\ кол-во уникальных сессий с посещением корзины
	slices: CR cart to reservation

6:
	service: Отели - клиентская часть
	name: Средняя сумма агентского вознаграждения и сервисного сбора
	metric: AAF (avg agency fee)
	type: guardrail-метрика
	methodology: (Агентское вознаграждение + сервисный сбор по заказам) / на кол-во заказов за период
	slices: AAF (avg agency fee)

7:
	service: Отели - клиентская часть
	name: Средний чек
	metric: AOV (avg order value)
	type: proxy-метрика
	methodology: Суммарная стоимость заказов / на кол-во заказов за период
	slices: AOV (avg order value)

8:
	service: Отели - клиентская часть
	name: Суммарные агентское вознаграждение и сервисный сбор
	metric: nan
	type: Целевая метрика
	methodology: Сумма агентского вознаграждения и сервисного сбора по заказам
	slices: nan

9:
	service: Отели - клиентская часть
	name: Среднее кол-во ночей в бронировании
	metric: nan
	type: proxy-метрика
	methodology: Суммарное кол-во ночей в заказах на кол-во заказов
	slices: nan

10:
	service: Отели - клиентская часть
	name: Средняя стоимость 1 ночи
	metric: nan
	type: proxy-метрика
	methodology: Суммарная стоимость заказов / кол-во ночей в заказах
	slices: nan

11:
	service: Отели - клиентская часть
	name: Доля пустых выдач
	metric: nan
	type: proxy-метрика
	methodology: Cобытия пустой выдачи/Событие загрузки выдачи. Прокси для конверсии поиск->Заказ
	slices: nan

12:
	service: Отели - клиентская часть
	name: Скорость загрузки выдачи
	metric: nan
	type: Целевая метрика
	methodology: Время (в сек) между событиями "запуск поиска" и "загрузкой выдачи"
	slices: nan

13:
	service: Отели - клиентская часть
	name: Кол-во заказов с промокодом 
	metric: nan
	type: proxy-метрика
	methodology: Кол-во плаченных заказов с применённым промо-кодом
	slices: nan

14:
	service: Отели - клиентская часть
	name: Средняя доходность заказа с промокодом в рамках сервисного сбора
	metric: nan
	type: proxy-метрика
	methodology: (Комиссия + сервисный сбор от заказов с промо-кодами - сумма применённых промо-кодов)/кол-во заказов с промо-кодом
	slices: nan

15:
	service: Отели - клиентская часть
	name: LTV отельного покупателя
	metric: nan
	type: guardrail-метрика
	methodology: LTV пользователя при покупке только отелей Туту
	slices: nan

16:
	service: Отели - клиентская часть
	name: LTV отельного покупателя и покупателя транспорта
	metric: nan
	type: guardrail-метрика
	methodology: Совокупный LTV пользователя, который совершал покупки как транспорта, так и отелей. Возможен гэп до 3 месяцев
	slices: nan

17:
	service: Отели - клиентская часть
	name: LTV покупателя транспорта
	metric: nan
	type: proxy-метрика
	methodology: LTV пользователя при покупке только транспорта Туту
	slices: nan

18:
	service: Отели - клиентская часть
	name: Доля покупателей транспорта среди купивших отель
	metric: nan
	type: Целевая метрика
	methodology: Кол-во покупателей отеля и транспорта/Кол-во покупателей транспорта
	slices: nan

19:
	service: Отели - клиентская часть
	name: Доля новых / старых покупателей только отелей (нет заказов транспорта)
	metric: nan
	type: proxy-метрика
	methodology: Новый покупатель отелей - тот, кто совершил первый заказ отелей за 6 месяцев; Старый - совершил повторную покупку за 6 месяцев
	slices: nan

20:
	service: Отели - клиентская часть
	name: Доля новых / старых покупателей отелей, но имевших заказ транспорта
	metric: nan
	type: proxy-метрика
	methodology: Новый покупатель отелей - тот, кто сделал первый заказ отелей за 6 месяцев, при этом также имел покупку транспорта за 6 месяцев; Старый - совершил повторную покупку за 6 месяцев, при этом также имел покупку транспорта за 6 месяцев
	slices: nan

21:
	service: Отели - ассортимент и оффер
	name: Насыщенность предложения жилья в целевой географии для целевой аудитории
	metric: nan
	type: Целевая метрика
	methodology: 2023: топ-30 направлений продаж транспорта Туту; портреты ЦА определим в Q2
	slices: nan

22:
	service: Отели - ассортимент и оффер
	name: Наша доля в заполненности партнерских средств размещения
	metric: nan
	type: Целевая метрика
	methodology: Среднее количество номеров, одновременно занятых нашими бронями, относительно общего числа номеров партнера
	slices: nan

23:
	service: Отели - ассортимент и оффер
	name: Доля полно описаных отелей из топ-сегмента спроса относительно всех отелей этого сегмента
	metric: nan
	type: Целевая метрика
	methodology: Сегмент: топ-100 по рекомендованности в топ-30 направлениях продаж транспорта Туту. В карточке отеля заполнены: текстовое описание, адрес, фото >10, удобства, описания номеров.
	slices: nan

24:
	service: КЦ
	name: Отток клиентов, прошедших через КЦ
	metric: nan
	type: guardrail-метрика
	methodology: Смотрим на разницу оттока прошедших через КЦ и не прошедших
	slices: nan

25:
	service: КЦ
	name: NPS клиентов, прошедших через КЦ
	metric: nan
	type: guardrail-метрика
	methodology: Смотрим на разницу NPS прошедших через КЦ и не прошедших
	slices: nan

26:
	service: КЦ
	name: Доля клиентов, обратившихся в КЦ
	metric: Contact Rate
	type: guardrail-метрика
	methodology: Соотношение клиентов, обратившихся в КЦ, ко всем клиентам Туту. И вопрос - считаем от покупателей или пользователей сайта/приложения? Возможно, это два разных показателя - CR покупателей и CR пользователей
	slices: Contact Rate

27:
	service: КЦ
	name: Стоимость обработки кейса
	metric: nan
	type: Целевая метрика
	methodology: Стоимость обработки кейса = (процент времени на обработку кейса линии Х от всего времени линии Х * стоимость всего времени линии Х) + (процент времени на обработку кейса линии У * стоимость времени линии У) / количество кейсов 
	slices: nan

28:
	service: КЦ
	name: Стоимость обработки контакта на первой линии средняя (первая линия, все каналы)
	metric: nan
	type: Целевая метрика
	methodology: Стоимость первой линии делим на все обращения, обработанные на первой линии
	slices: nan

29:
	service: КЦ
	name: Стоимость обработки контакта на первой линии в звонке 
	metric: nan
	type: Целевая метрика
	methodology: Стоимость первой линии * процент времени, затраченного на обработку звонков, от всего времени первой линии / количество звонков
	slices: nan

30:
	service: КЦ
	name: Стоимость обработки контакта на первой линии в письме 
	metric: nan
	type: Целевая метрика
	methodology: То же для писем
	slices: nan

