version: "1.0"

1:
  from: 3
  to: 2
  type: Hard

2:
  from: 4
  to: 2
  type: Soft

3:
  from: 2
  to: 1
  type: Hard

4:
  from: 5
  to: 2
  type: Hard

5:
  from: 6
  to: 3
  type: Hard

6:
  from: 7
  to: 6
  type: Hard
